### ISSUE TITLE
Latest CS:GO isn't compatible

### ISSUE THREAD

**Issue by ExtremeMan** [TheDS/srcds_osx#2]
Hey!

I have just downloaded updated version of CS:GO and it looks like `launcher.dylib` was updated. Now there are no symbols that are searched by srcds_osx.

**Comment by GoD-Tony** [comment]
Looks like all CS:GO mac bins are now stripped of symbols. It'd be quite a pain to get this working again.

**Comment by ExtremeMan** [comment]
Good thing is that if you have a copy of older version of `bin` folder then you can just copy-paste and it will work.

**Comment by 1sammy** [comment]
Awwww, what a pain to get a server running... ExtremeMan, it would be greatly appreciated if you would upload your older version of the bin folder, that is, assuming you have one.

**Comment by TheDS** [comment]
Apologies for taking so long to get to this. School/college ate away at my time. I've updated the code and binaries in the [AlliedModders post](https://forums.alliedmods.net/showthread.php?t=158240) to finally fix this.

Please note that CS:GO is now 64-bit, so Metamod:Source and SourceMod will not currently run on these. For now, these will have to be vanilla servers.
