### ISSUE TITLE
Insurgency Dedicated Server issue

### ISSUE THREAD

**Issue by Xendrez** [TheDS/srcds_osx#3]
Downloaded Insurgency Dedicated Server through steamCMD
Downloaded srcds_osx-insurgen...tar.gz
Replaced srcds_osx & srcds_run as well as shaderapiempty.dylib in the bin
Tried to run: ./srcds_run -ip 0.0.0.0 -port 27015 +map market_coop +maxplayers 32 -debug
Output:

_Auto detecting CPU
Using OSX binary.
Enabling debug mode
Server will auto-restart if there is a crash.
Failed to find symbols for materialsystem.dylib
cat: hlds.43217.pid: No such file or directory_

Nothing useful in debug.log

Is there something I'm doing wrong, or is there a bug currently?

**Comment by Xendrez** [comment]
It seems like it might be the same issue as with CS:GO server. How was that fixed?

**Comment by Xendrez** [comment]
Changed the code to spit out which symbols are missing:

_Failed to find symbols for materialsystem.dylib
_g_pShaderAPIDX8
_g_pShaderDeviceDx8
_g_pShaderDeviceMgrDx8
_g_pShaderShadowDx8_

**Comment by Xendrez** [comment]
I tried ignoring the check and returning true. Then I get:

_./srcds_run: line 353: 43700 Bus error: 10           $HL_CMD
cat: hlds.43689.pid: No such file or directory_

**Comment by TheDS** [comment]
Apologies for taking so long to get to this. School/college ate away at my time. I've updated the code and binaries in the [AlliedModders post](https://forums.alliedmods.net/showthread.php?t=158240) to finally fix this.
